# roles/wordpress/tasks/config.yml
# Configures Wordpress
---

- name: Apache config file for Wordpress
  template:
    src: wordpress.conf.j2
    dest: "{{ wordpress_httpd_configuration }}"
    owner: root
    group: root
    mode: '0644'
    setype: httpd_config_t
  notify: restart httpd
  tags: wordpress

- name: Wordpress config file
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_configuration }}"
    owner: root
    group: apache
    mode: '0640'
    setype: etc_t
  notify: restart httpd
  tags: wordpress

- name: Allow Apache to access database over the network if necessary
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true
  when: ansible_selinux.status == 'enabled' and wordpress_database_host != 'localhost'
  tags: wordpress
