# roles/wordpress/tasks/install.yml
---

- name: Ensure repository is installed
  package:
    name: "{{ wordpress_repository }}"
    state: present
  tags: wordpress

- name: Check whether Apache is already installed
  stat:
    path: "{{ wordpress_httpd_service }}"
  register: wordpress_httpd_status
  failed_when: not wordpress_httpd_status.stat.exists
  tags: wordpress

- name: Install Wordpress Prerequisites
  package:
    name: "{{ wordpress_packages }}"
    state: present
  tags: wordpress

- name: Download Wordpress
  get_url:
    url: https://wordpress.org/wordpress-5.0.8.tar.gz
    dest: "{{ wordpress_install_directory }}"
  
- name: Unzipping wordpress
  unarchive:
    src: "{{ wordpress_install_directory }}/wordpress-5.0.8.tar.gz"
    dest: "{{ wordpress_install_directory }}"
    remote_src: yes

- name: Remove wordpress.tar.gz file
  file:
    path: "{{ wordpress_install_directory }}/wordpress-5.0.8.tar.gz"
    state: absent

- name: Setting ownership 
  file:
    path: "{{ wordpress_directory }}"
    owner: apache
    group: apache
    state: directory
    recurse: yes
    mode: '0775'

- name: Setting SELinux context    
  community.general.sefcontext:
    target: "{{ wordpress_directory }}"
    setype: httpd_sys_rw_content_t
    state: present
