# roles/wordpress/tasks/main.yml
---

- include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - wordpress
- include: install.yml
- include: config.yml
- include: plugins.yml
- include: themes.yml

